apiVersion: skaffold/v2beta21
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: 4khiln/ticketing_auth 
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: 4khiln/tickets 
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
